### ISSUE TITLE
upgrade SimplePing

### ISSUE THREAD

**Issue by alexei1118** [naptics/PlainPing#11]
You are using SimplePing from Apple for ping request, but I found that your SimplePing is outdated.
You used the version of 2012, but Apple published the version of 2016.
The problem that use 2012 version, is that it does not support IPv6, so your PlainPing crashes on ipv6-only network.
I already fixed this problem and I want to contribute my changes.
Look forward to hear from you.

**Comment by seeppp** [comment]
Hi
you're right, the code is outdated.
Please sign a PR and I will accept the changes!
Thanks for helping!
