### ISSUE TITLE
Xcode 9 support + update version in cocoapods repo to latest

### ISSUE THREAD

**Issue by Speakus** [naptics/PlainPing#13]

**Comment by kmiloaguilar** [comment]
#14

**Comment by seeppp** [comment]
go for it: https://cocoapods.org/pods/PlainPing

**Comment by Speakus** [comment]
@seeppp cool. could you update this file to: https://github.com/naptics/PlainPing/blob/master/PlainPing.podspec to make it consistancy please

**Comment by seeppp** [comment]
😘  3a3e52b4e0463a499f732b102575a12171ad0a46
