### ISSUE TITLE
Leaking

### ISSUE THREAD

**Issue by roor** [naptics/PlainPing#16]
Can you fix leaking in library.
<img width="493" alt="screen shot 2018-02-13 at 14 22 41" src="https://user-images.githubusercontent.com/4786946/36154653-675003be-10d2-11e8-8c02-7f600c3f667a.png">

adding those two lines will do the job
<img width="837" alt="bildschirmfoto 2018-02-13 um 15 27 46" src="https://user-images.githubusercontent.com/4786946/36154682-81ff8108-10d2-11e8-9310-00f05fef2107.png">

thnx

**Comment by seeppp** [comment]
thanks for reporting. fixed in 0.5
