### ISSUE TITLE
No such module PlainPing

### ISSUE THREAD

**Issue by S1ayer** [naptics/PlainPing#3]
Hello,

I have downloaded your Example project and executed "pod install" in the example folder:

> Analyzing dependencies
Fetching podspec for `PlainPing` from `../`
Downloading dependencies
Using PlainPing (0.2)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total
pod installed.

Afterwards I opened the example project but I'm not able to compile it. Would be really great if you could help me to find the error. Thanks a lot.

![bildschirmfoto 2016-03-22 um 21 03 49](https://cloud.githubusercontent.com/assets/7255837/13966250/c46a45d8-f071-11e5-83fb-bde1668c7d19.png)

Regards,
Johannes

**Comment by S1ayer** [comment]
Hello again,

sorry for disturbing. But something went wrong the first time. Did now again clone the repo and "pod install". Now it works. Thanks.

Regards,
Johannes

**Comment by SamboVisal** [comment]
It is still not working for me. still alert me "No such module PlainPing"
